### PR TITLE
🚧 feat: add support for reusing a vm

### LINKED ISSUE #334: Add support for reusing a virtual machine
#### Community Note

Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request.
If you are interested in working on this issue or have submitted a pull request, please leave a comment.

#### Description

Currently there's no functional to install an ISO to an existing VM. Rephrasing in packer terms: there's no way to build a machine image in vsphere by re-using an existing VM.

As a matter of fact, [judging by the lack of answers here](https://groups.google.com/g/packer-tool/c/BIEmO7hC1n0), it doesn't seem to be possible for any hypervisor, not just vsphere.

#### Use Case(s)

* Limiting the existing VMs to certain number of pre-created ones. `packer` is for automated VMs creation, and if there's a bug in the logic that calls packer, there may be an explosion of creating new VMs.
* ***(our usecase)*** working around missing functionality in the plugin. For example, there's currently no way to create a pair of VMs connected as an active/active or active/passive cluster *(that is having VMs with simultaneous access to the same "disk" or rather "disk file")*. Such functional is also difficult to implement because it does not work well in vSphere to start with. E.g. if you try to destroy such VM that shares a disk you'll get a vague `concurrent access` error.

### PR DESCRIPTION
**Pull request by Hi-Angel**
This PR resolves the problem where users could not install a system from ISO to a pre-created Virtual Machine.

Closes #334

TODO:

* [ ] Error out if HCL/JSON config has `reuse_vm = true` and also hardware configuration *(because we don't want to modify hw on a pre-created VM)*. [under discussion](https://github.com/hashicorp/packer-plugin-vsphere/pull/344#issuecomment-2007596662)

### CODE REVIEW

**Comment by Hi-Angel** [comment]
This is rebased version of [closed PR](https://github.com/hashicorp/packer-plugin-vsphere/pull/344). The feature is currently under discussion per [this comment](https://github.com/hashicorp/packer-plugin-vsphere/issues/334#issuecomment-2076328459)

**Comment by tenthirtyam** [comment]
_Go Validate / Generate check (pull_request) Failing after 1m_

Needs to run `make generate` and amend the commit.

**Comment by Hi-Angel** [comment]
Oh, I'm sorry, I haven't realized the message `Docs have been updated, but the compiled docs have not been committed` is an actual error. Seeing auto-generated things get commited isn't typical, so I dismissed the message and in absence of any other error I thought it's just a CI bug.

Done! Should be okay now

**Comment by tenthirtyam** [comment]
Hi @Hi-Angel! 👋 

Since there haven't been any reactions on this niche use case (nor seen in other plugins), we're going to decline this feature gracefully as **not planned**. You are of course welcome to fork the project and use the implementation for your environmental needs.

**Ryan Johnson**
Distinguished Engineer, VMware by Broadcom

**Pull request closed without merging**
