### PR TITLE
docs(examples): remove macos

### PR DESCRIPTION
**Pull request by tenthirtyam**
### Summary

Removes the examples for macOS.

On June 22, 2020, Apple announced the transition from x86 to Apple silicon. 

VMware vSphere 7.0.x was the final release supporting Apple Mac Platforms on x86.

### References

- [Apple Press Release](https://www.apple.com/newsroom/2020/06/apple-announces-mac-transition-to-apple-silicon/)
- [VMware KB 886989](https://kb.vmware.com/s/article/88698)

### CODE REVIEW

**Review by nywilken — APPROVED** [review]
Thanks for this context. These changes all pertain to example templates and looks good. 

> VMware vSphere 7.0.x was the final release supporting Apple Mac Platforms on x86.

The link https://kb.vmware.com/s/article/886980 is throwing a 404. 

Does this just mean that users running a later version of vSphere can not build macOs vms? 

Will this affect the Packer plugin on macOs host in the future in any way? This plugin leverages the API for interactions but curious if govmomi will be affected in the future.

**Comment by tenthirtyam** [comment]
Correct, macOS on vSphere 8.0 and later will not be supported. No impact to the binary to run the plugin on macOS.

**Comment by tenthirtyam** [comment]
Updated the link to https://kb.vmware.com/s/article/88698.

**Comment by nywilken** [comment]
Sweet, thank you sir!

**Pull request merged**
