### PR TITLE
chore(tests): remove unnecessary `AddCdromCalled`

### PR DESCRIPTION
**Pull request by Hi-Angel**
There is an AddCdromCalledTimes which serves the same purpose

### CODE REVIEW

**Comment by tenthirtyam** [comment]
✅ CI Passed.

```console
Run echo "Testing with Go 1.20.10"
Testing with Go 1.20.10
?   	github.com/hashicorp/packer-plugin-vsphere	[no test files]
ok  	github.com/hashicorp/packer-plugin-vsphere/builder/vsphere/clone	0.112s
?   	github.com/hashicorp/packer-plugin-vsphere/builder/vsphere/common/testing	[no test files]
?   	github.com/hashicorp/packer-plugin-vsphere/builder/vsphere/examples/driver	[no test files]
ok  	github.com/hashicorp/packer-plugin-vsphere/builder/vsphere/common	1.073s
?   	github.com/hashicorp/packer-plugin-vsphere/version	[no test files]
ok  	github.com/hashicorp/packer-plugin-vsphere/builder/vsphere/driver	4.[6](https://github.com/hashicorp/packer-plugin-vsphere/actions/runs/7330363187/job/19965407964?pr=352#step:4:7)92s
ok  	github.com/hashicorp/packer-plugin-vsphere/builder/vsphere/iso	0.092s
ok  	github.com/hashicorp/packer-plugin-vsphere/builder/vsphere/supervisor	2.193s
ok  	github.com/hashicorp/packer-plugin-vsphere/post-processor/vsphere	0.062s
ok  	github.com/hashicorp/packer-plugin-vsphere/post-processor/vsphere-template	0.09[7](https://github.com/hashicorp/packer-plugin-vsphere/actions/runs/7330363187/job/19965407964?pr=352#step:4:8)s
```

**Review by tenthirtyam — APPROVED** [review]
LGTM. But I suggest merging this **after** the changes for reattaching the CD-ROM and another CI pass,

**Review by nywilken — APPROVED** [review]
Thanks for this change. I agree it is not needed given the existence of AddCdromCalledTimes

**Comment by nywilken** [comment]
@Hi-Angel I rebased and pushed the latest changes from main to fix the reattach CDROMs tests. I will merged once all goes green.

**Comment by Hi-Angel** [comment]
Thank you!

**Pull request merged**
