### PR TITLE
Add description of OVF content library item

### LINKED ISSUE #175: Content Library Import Configuration support for the description field of OVF templates
The Content Library Import Configuration currently ignores the description of OVF template:

> Description of the library item that will be created. This option is not used when importing OVF templates. Defaults to "Packer imported [vm_name](https://www.packer.io/plugins/builders/vsphere/vsphere-iso#vm_name) VM template".

https://www.packer.io/plugins/builders/vsphere/vsphere-iso#description
https://www.packer.io/plugins/builders/vsphere/vsphere-clone#description

It would be useful for my use-cases to support this.

### PR DESCRIPTION
**Pull request by hmalphettes**
Closes #175

Enable setting the description field of an OVF template
published into a content library.

Requires updating govmomi to 0.27 where the UpdateLibraryItem
is supported.

### CODE REVIEW

**Comment by tenthirtyam** [comment]
You can add "Closes #175" to the content above to link the issue vs placing it in the title of the pull request. When the pull request is merged it would then close the issue.

**Ryan Johnson**
Staff II Solutions Architect | VMware, Inc.

**Review by nywilken — COMMENTED** [review]
Hi @hmalphettes thanks for opening up this PR, and apologies for the delayed review. @tenthirtyam thanks for the assist with getting the original PR split out. 

Change wise this looks good, but I have a question about the govmomi bump. I see that you pulled in v0.28.0 for the UpdateLibraryItem method. Is there a reason why you chose 0.28.0 over 0.26.1, where UpdateLibraryItem was added? 

I ask because there appears to be a number of breaking changes in the release after 0.26.1. Ideally I would prefer not to introduce breaking changes to the plugin unless they've been tested against and all local tests pass. I've asked @tenthirtyam to help in validating that there are no side effects with the govmomi bump. But I also wanted to bring it to your attention. 

That said, I see that the build checks (go tests) are not running on this PR. I'm not sure why. But running tests locally show a failure as the mocks need to be updated. Can you please run `go test ./...` and fix the reported issues.

**Comment by hmalphettes** [comment]
@nywilken thanks for the kind review. No problem at all with the delays.
So I'll set govmomi to 0.26.1 and make sure to run the tests.
Cheers!

**Review by nywilken — APPROVED** [review]
@hmalphettes thanks for the quick turnaround. All looks good. Cheers!

**Pull request merged**
