### PR TITLE
Update VMware product names and product terminology

### PR DESCRIPTION
**Pull request by tenthirtyam**
With a desire to help improve the quality and accuracy of the documentation generated for the plugin, I am submitting this pull request to update the use of VMware product names and product terminology, where found.

- Updates any occurrence of "Vsphere" to "vSphere".
- Updates any occurrence of "VMWare" to "VMware".
- Updates any occurrence of incorrect use of  "vCenter" to "vCenter Server".
- Updates some incorrect use of vSphere terminology.
- Updates any occurrence of "ESX" to "ESXi host"
- Updates any occurrence of "VMware article" to "VMware KB article"
- Updates information on VMware Guestinfo datasource which is now native in cloud-init 21.3 and later. Prior datasource is deprecated and the project is archived.
- Updates any occurrence of "code.vmware.com" to "developer.vmware.com".

Please don't hesitate to let me know if you have any questions or concerns.

### CODE REVIEW

**Comment by azr** [comment]
Nice one, LGTM. Don't forget to run `make generate` !

**Comment by tenthirtyam** [comment]
I'll run that today and post the commit. Thanks!

**Comment by tenthirtyam** [comment]
Hi @azr, if time permits can you suggest how to address this error when generating the docs?

```console
❯ make generate
builder/vsphere/clone/config.go:1: running "packer-sdc": exec: "packer-sdc": executable file not found in $PATH
builder/vsphere/common/config_location.go:1: running "packer-sdc": exec: "packer-sdc": executable file not found in $PATH
builder/vsphere/iso/config.go:1: running "packer-sdc": exec: "packer-sdc": executable file not found in $PATH
post-processor/vsphere/post-processor.go:1: running "packer-sdc": exec: "packer-sdc": executable file not found in $PATH
post-processor/vsphere-template/post-processor.go:1: running "packer-sdc": exec: "packer-sdc": executable file not found in $PATH
make: *** [generate] Error 1
```

Seems I need `packer-sdc` - where's this sourced?

Ryan

**Comment by tenthirtyam** [comment]
Thanks @nywilken, I was able to fix the issue and have committed the added results of `make generate` in https://github.com/hashicorp/packer-plugin-vsphere/pull/161/commits/f09b7a768f83f5ef8bf0fdd11e3d343d6a1b924a.

Ryan

**Comment by nywilken** [comment]
@tenthirtyam I pulled down this PR and rebased onto the latest main. If it's okay with you I can push up and merge. Just want to check with you as it will be a force push (because of rebase). LMK

**Comment by tenthirtyam** [comment]
Got for it, @nywilken! 🚀 

Ryan

**Comment by tenthirtyam** [comment]
Thank you, @nywilken!

**Pull request merged**
