### PR TITLE
fix: 224

### LINKED ISSUE #224: `vsphere-template`: VM at path `/MyDataCenter/vm/Discovered virtual machine/ubuntu` not found
#### Overview of the Issue

I am trying to place the VM template under a Datacenter folder 

`convert_to_template = true` places the VM template into path ` /MyDataCenter/templates/`

But I'm getting this error

`(vsphere-template): VM at path /MyDataCenter/vm/Discovered virtual machine/ubuntu not found`

```hcl
source "vsphere-iso" "my_ubuntu" {
  # ...
}

build {
  name    = "my_ubuntu"
  sources = ["source.vsphere-iso.my_ubuntu"]

  post-processors {
    # Create VM template
    post-processor "vsphere-template" {
      host       = var.vcenter_server
      username   = var.vsphere_username
      password   = var.vsphere_password
      insecure   = var.vsphere_insecure_connection
      datacenter = var.vsphere_datacenter
      folder     = "/templates/"
    }
  }
}
```

### Packer Version

Please provide the Packer version.

### Plugin Version and Builders

Please provide the plugin version.

Please select the builder.

- [x] `vsphere-iso`
- [ ] `vsphere-clone`

### VMware vSphere Version

`7.0.3.00700`

### Guest Operating System

- Ubuntu 22.04: `ubuntu-22.04.1-live-server-amd64.iso`

### Simplified Packer Buildfile

If the file is longer than a few dozen lines, please include the URL to the [gist](https://gist.github.com/) of the log or use the [GitHub detailed format](https://gist.github.com/ericclemmons/b146fe5da72ca1f706b2ef72a20ac39d) instead of posting it directly in the issue.

### Operating System and Environment Details

WSL2

### PR DESCRIPTION
**Pull request by saikirandusari**
Use the folder defined in the post-processor packer config as a remoteFolder when marking the VM as a template.
```hcl
post-processors {
      post-processor "vsphere-template"{
          host              = "vcenter.example.com"
          insecure        = false
          username       = "admin@vsphere.local"
          password       = "testpwd"
          datacenter     = "dc-01"   
          folder              = "/templates/"
      }
}
```

This PR resolves open issue #224

Closes #224

### CODE REVIEW

**Review by tenthirtyam — DISMISSED** [review]
LGTM!

**Comment by tenthirtyam** [comment]
CI is failing. Please review the errors. :)

**Review by tenthirtyam — CHANGES_REQUESTED** [review]
CI is failing. Please review the errors. :)

**Comment by saikirandusari** [comment]
> CI is failing. Please review the errors. :)

[tenthirtyam](https://github.com/tenthirtyam) Code fix applied. Please review and approve to run the tests.

**Comment by tenthirtyam** [comment]
image

**Comment by tenthirtyam** [comment]
@lbajolet-hashicorp - I addressed the the issue mentioned in https://github.com/hashicorp/packer-plugin-vsphere/pull/312#issuecomment-1770507526 and it's moved forward but Go Validate action is failing on the `lint` and `gofmt` steps but those don't seem to be related to this change.

```shell

  /usr/bin/tar: ../../../go/pkg/mod/golang.org/x/sys@v0.6.0/PATENTS: Cannot open: File exists
  /usr/bin/tar: ../../../go/pkg/mod/golang.org/x/sys@v0.6.0/.gitignore: Cannot open: File exists
  /usr/bin/tar: ../../../go/pkg/mod/golang.org/x/sys@v0.6.0/go.mod: Cannot open: File exists
  /usr/bin/tar: Exiting with failure status due to previous errors
  Warning: Failed to restore: "/usr/bin/tar" failed with error: The process '/usr/bin/tar' failed with exit code 2
  Cache not found for input keys: golangci-lint.cache-2807-48db04078f992043765d66fe773ddecb962b11e2, golangci-lint.cache-2807-
  Finding needed golangci-lint version...
  Installation mode: binary
  Installing golangci-lint binary v1.53.3...
  Downloading binary https://github.com/golangci/golangci-lint/releases/download/v1.53.3/golangci-lint-1.53.3-linux-amd64.tar.gz ...
  Writing patch to /tmp/tmp-1808-uienO06vLFpm/pull.patch
  /usr/bin/tar xz --overwrite --warning=no-unknown-keyword --overwrite -C /home/runner -f /home/runner/work/_temp/093b28de-207f-4e2b-9661-26b1a7dc5091
  Installed golangci-lint into /home/runner/golangci-lint-1.53.3-linux-amd64/golangci-lint in 599ms
  Prepared env in 13378ms
```

**Comment by lbajolet-hashicorp** [comment]
Hey @tenthirtyam,

The lint/check failures were because the indentation does not match what go expects, in general it's recomemnded to use tabs for indentation, and your last update changed that in favour of spaces, hence the failure.

The last reroll I pushed makes the tests all green, I'll review this change now and if it looks good to me, I'll merge this PR.

Thanks for the ping!

**Comment by tenthirtyam** [comment]
Many thanks, @lbajolet-hashicorp!

**Review by lbajolet-hashicorp — APPROVED** [review]
LGTM!

**Comment by saikirandusari** [comment]
Thanks @lbajolet-hashicorp and @tenthirtyam for sorting this PR

**Pull request merged**
