### PR TITLE
Fixed broken a link to term "vim.vmConfigSpec.html"

### PR DESCRIPTION
**Pull request by mikeschinkel**

### CODE REVIEW

**Comment by nywilken** [comment]
Hi @mikeschinkel the URL in your change refers to an older version of the documentation. Is there a particular issue you ran into that caused you to update the link? 

I'm going to close this PR but if you believe there is an issue with the documentation can you please open a new issue using the provided [template](https://github.com/hashicorp/packer-plugin-vsphere/issues/new?assignees=&labels=bug&template=bug_report.md) so that we can address the issues at once. Thanks for the contribution.

**Comment by mikeschinkel** [comment]
@nywilken — The specific issue was I was trying to read the docs to be able to understand `ConfigSpec` and found the link to be broken.

**Comment by nywilken** [comment]
Totally understandable the link referenced does appear to work. I wonder if the documentation out there is broken. I’ll follow up for references to this material.

**Comment by tenthirtyam** [comment]
The provided link should be the most current as it refers to `Version 7.0U3` at the bottom of the page, which is the latest release.

🤔 It would be rather nifty if HashiCorp / GitHub had a URL redirect service that could be used by maintainers so that URLs did not have to change in code, but simply reside in an upstream redirect. `¯\_(ツ)_/¯`

Ryan

**Comment by mikeschinkel** [comment]
> 🤔 It would be rather nifty if HashiCorp / GitHub had a URL redirect service that could be used by maintainers so that URLs did not have to change in code, but simply reside in an upstream redirect. ¯\_(ツ)_/¯

Now THAT would be awesome!!! 

In the meantime it would be great if documentation authors recognized that evergreen links are an important building block for the web and not write docs with different URLs each time they update to a new versions.  IOW, add links, but never deprecate them _(unless the topic/concept itself is deprecated.)_ 

Unfortunately, VMware is far from the only org where docs authors write docs as it they were going to be printed rather than published on the web.

**Comment by mikeschinkel** [comment]
@nywilken — 
> _"I’ll follow up for references to this material."_

Cool!

**Comment by mikeschinkel** [comment]
@tenthirtyam — Feedback submitted to docs.vmware.com.

**Pull request closed without merging**
