### PR TITLE
docs: fix links and options

### PR DESCRIPTION
**Pull request by benjamin-lykins**
### Changes

- Cleaned up Windows and Linux customization options on `vsphere-clone` documentation.
- Fixed broken links for Linux and Windows options.
- Added missing Windows options and examples.

### Tests

```sh
─░▒▓    ~/git/personal/packer-plugin-vsphere  on   docs/windows_options ▓▒░·····························································································░▒▓ ✔  at 12:04:04  ▓▒░─╮
╰─ make generate                                                                                                                                                                                        ─╯
2024/04/03 12:04:21 Copying "docs" to ".docs/"
2024/04/03 12:04:21 Replacing @include '...' calls in .docs/
Compiling MDX docs in '.docs' to Markdown in '.web-docs'...

╭─ ~/git/personal/packer-plugin-vsphere  on   docs/windows_options ▓▒░················································································░▒▓ ✔  took 11s   at 12:04:21  ▓▒░─╮
╰─ make test                                                                                                                                                                                            ─╯
?       github.com/hashicorp/packer-plugin-vsphere      [no test files]
?       github.com/hashicorp/packer-plugin-vsphere/builder/vsphere/common/testing       [no test files]
?       github.com/hashicorp/packer-plugin-vsphere/builder/vsphere/examples/driver      [no test files]
?       github.com/hashicorp/packer-plugin-vsphere/version      [no test files]
ok      github.com/hashicorp/packer-plugin-vsphere/builder/vsphere/clone        2.678s
ok      github.com/hashicorp/packer-plugin-vsphere/builder/vsphere/common       2.080s
ok      github.com/hashicorp/packer-plugin-vsphere/builder/vsphere/driver       5.036s
ok      github.com/hashicorp/packer-plugin-vsphere/builder/vsphere/iso  2.208s
ok      github.com/hashicorp/packer-plugin-vsphere/builder/vsphere/supervisor   4.228s
ok      github.com/hashicorp/packer-plugin-vsphere/post-processor/vsphere       1.436s
ok      github.com/hashicorp/packer-plugin-vsphere/post-processor/vsphere-template      2.551s
```

### CODE REVIEW

**Review by nywilken — APPROVED** [review]
HI @benjamin-lykins this looks good to me. I'm going to ping @tenthirtyam who has been working on a similar set of changes to get additional approval.

**Comment by tenthirtyam** [comment]
Let's hold until my changes in the `docs/technical-debt` branch are locked into a PR and merged. We can then rebased to determine any deltas.

**Comment by tenthirtyam** [comment]
Marked as draft and will rebase after my pending changes are locked in.

**Comment by nywilken** [comment]
Thanks @tenthirtyam I labeled this as waiting on an upstream PR for now.

**Review by tenthirtyam — APPROVED** [review]
LGTM!

I've pushed some minor adjustments to align with the upcoming changes that I'll working on.

**Pull request merged**
