### PR TITLE
Update link to `vim.vm.ConfigSpec`

### LINKED ISSUE #156: External URL to VMware for configuration_parameters is dead
#### Overview of the Issue

Referenced VMware documentation link in file `docs/builders/vsphere-clone.mdx` not available any more:

Page: https://www.packer.io/plugins/builders/vsphere/vsphere-clone#extra-configuration-parameters

Dead Link: https://www.vmware.com/support/developer/vc-sdk/visdk41pubs/ApiReference/vim.vm.ConfigSpec.html

It can probably be replaced by this working one:

https://vdc-repo.vmware.com/vmwb-repository/dcr-public/91f5f971-bf1d-4904-9942-37c6109da8a3/b79fa83f-dc4e-491d-9785-dc9d91aa0c67/doc/vim.vm.ConfigSpec.html

#### Reproduction Steps

Click on the Link.

### Packer Version

n/a

### Plugin Version and Builders

Please provide the plugin version.

n/a

Please select the builder.

- [X] `vsphere-iso`
- [X] `vsphere-clone`

### VMware vSphere Version

n/a

### Guest Operating System

n/a

### Simplified Packer Buildfile

n/a

### Log Fragments and `crash.log` Files

n/a

### PR DESCRIPTION
**Pull request by tenthirtyam**
Updates the link to the `vim.vm.ConfigSpec`.

Closes #156

### CODE REVIEW

**Comment by tenthirtyam** [comment]
Committed the added results of `make generate` in [f09b7a7](https://github.com/hashicorp/packer-plugin-vsphere/pull/160/commits/ca3c3cf43dc5cb11146bdd913300ba088217a02c).

Ryan

**Review by azr — APPROVED** [review]
Woops, looks like you committed the .docs folder which are generated files, but should not be commited; maybe we could ignore the folder to avoid that in the future as well ? Other than that: LGTM !

**Comment by tenthirtyam** [comment]
@azr, perhaps an update to .gitignore?

**Comment by nywilken** [comment]
> @azr, perhaps an update to .gitignore?

hi @tenthirtyam apologies for this mixup. Our makefile generates the .docs directory when calling `make generate` which isn't needed. I pushed up a fix to your branch so I can merge in your changes. I hope that okay.

**Comment by tenthirtyam** [comment]
Totally cool by me, @nywilken - thank you for the due diligence and merge!

**Pull request merged**
